# Generated by Django 5.0.6 on 2024-06-01 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            sql = [
                ("CREATE EXTENSION IF NOT EXISTS pgcrypto;"),
                ("""
                 CREATE TABLE IF NOT EXISTS book (
                     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                     title VARCHAR(255),
                     author VARCHAR(255),
                     description TEXT);"""),],
            reverse_sql = [
                           ("DROP TABLE IF EXISTS book;"),
                           ("DROP EXTENSION pgcrypto;"),],
        )
    ]
